const ROTATE_THING = "ROTATE_THING";
const CHANGE_COORDINATES_OF_THING = "CHANGE_COORDINATES_OF_THING";
const REMOVE_THING = "REMOVE_THING";
const ADD_THING = "ADD_THING";
const CHANGE_USER = "CHANGE_USER";
const CHANGE_OFFICE = "CHANGE_OFFICE";

export {
  ROTATE_THING,
  CHANGE_COORDINATES_OF_THING,
  REMOVE_THING,
  ADD_THING,
  CHANGE_USER,
  CHANGE_OFFICE
};
